#!/usr/bin/env python3
"""
===============================================================
  Sand Plotter GCode Generator
  Generates: Rectangle border → Lollipop Spiral (as in image)
  Output: sand_pattern.gcode

  Run:  python3 generate_gcode.py
  Then: send sand_pattern.gcode to your plotter via
        UGS, bCNC, Candle, or Arduino Serial Monitor
===============================================================
"""

import math

# ── Machine & Pattern Settings ────────────────────────────────
BED_W        = 280.0   # mm — bed width  (X)
BED_H        = 380.0   # mm — bed height (Y)
MARGIN       = 12.0    # mm — border inset from edge
FEED_TRAVEL  = 4000    # mm/min — rapid travel speed
FEED_DRAW    = 1200    # mm/min — drawing speed

# Rectangle corners
RX0 = MARGIN
RY0 = MARGIN
RX1 = BED_W - MARGIN
RY1 = BED_H - MARGIN

# Lollipop spiral settings (matches the image)
SPIRAL_CX    = BED_W * 0.42   # center X of the spiral circle (~118mm)
SPIRAL_CY    = BED_H * 0.52   # center Y of the spiral circle (~197mm)
SPIRAL_R_MAX = 55.0            # mm — outer radius of spiral
SPIRAL_R_MIN = 3.0             # mm — inner radius (stops near centre)
SPIRAL_TURNS = 3.5             # number of full revolutions
SPIRAL_STEPS = 400             # line segments (more = smoother)

# Stick of the lollipop: from bottom-right corner area to spiral entry
STICK_START_X = RX1 - 10      # enters from right side area
STICK_START_Y = RY0 + 10      # near bottom-right


def archimedean_spiral(cx, cy, r_start, r_end, turns, steps, start_angle=math.pi):
    """
    Returns list of (x,y) points for an Archimedean spiral.
    Winds inward from r_start → r_end over `turns` revolutions.
    start_angle: where on the circle the spiral enters (radians).
    """
    points = []
    total_angle = turns * 2 * math.pi
    for i in range(steps + 1):
        t = i / steps                       # 0 → 1
        angle = start_angle + t * total_angle
        r     = r_start + t * (r_end - r_start)  # shrinks inward
        x = cx + r * math.cos(angle)
        y = cy + r * math.sin(angle)
        points.append((x, y))
    return points


def generate_gcode():
    lines = []

    # ── Header ────────────────────────────────────────────────
    lines += [
        "; ===================================================",
        ";  Sand Plotter Pattern: Rectangle + Lollipop Spiral",
        ";  Generated by generate_gcode.py",
        f";  Bed: {BED_W}x{BED_H}mm",
        "; ===================================================",
        "",
        "G21        ; millimeters",
        "G90        ; absolute positioning",
        "G92 X0 Y0  ; set current position as origin",
        f"F{FEED_DRAW}",
        "",
    ]

    # ── 1. HOME ───────────────────────────────────────────────
    lines += [
        "; --- Go to start corner ---",
        f"G0 F{FEED_TRAVEL} X{RX0:.3f} Y{RY0:.3f}",
        "",
    ]

    # ── 2. RECTANGLE ─────────────────────────────────────────
    lines += [
        "; =====================================================",
        "; PHASE 1: Rectangle border",
        "; =====================================================",
        f"G1 F{FEED_DRAW} X{RX0:.3f} Y{RY0:.3f}  ; bottom-left",
        f"G1 X{RX1:.3f} Y{RY0:.3f}               ; → bottom-right",
        f"G1 X{RX1:.3f} Y{RY1:.3f}               ; ↑ top-right",
        f"G1 X{RX0:.3f} Y{RY1:.3f}               ; ← top-left",
        f"G1 X{RX0:.3f} Y{RY0:.3f}               ; ↓ close rectangle",
        "",
    ]

    # ── 3. STICK (diagonal line to spiral entry) ─────────────
    # The spiral entry point is at r_start, start_angle from center
    spiral_entry_angle = math.pi   # enters from the left of circle
    entry_x = SPIRAL_CX + SPIRAL_R_MAX * math.cos(spiral_entry_angle)
    entry_y = SPIRAL_CY + SPIRAL_R_MAX * math.sin(spiral_entry_angle)

    lines += [
        "; =====================================================",
        "; PHASE 2: Stick — travel from rectangle to spiral",
        "; =====================================================",
        f"G0 F{FEED_TRAVEL} X{STICK_START_X:.3f} Y{STICK_START_Y:.3f}",
        f"G1 F{FEED_DRAW}   X{entry_x:.3f} Y{entry_y:.3f}",
        "",
    ]

    # ── 4. SPIRAL ────────────────────────────────────────────
    spiral_pts = archimedean_spiral(
        cx=SPIRAL_CX, cy=SPIRAL_CY,
        r_start=SPIRAL_R_MAX, r_end=SPIRAL_R_MIN,
        turns=SPIRAL_TURNS, steps=SPIRAL_STEPS,
        start_angle=math.pi
    )

    lines += [
        "; =====================================================",
        "; PHASE 3: Inward Archimedean spiral (lollipop head)",
        "; =====================================================",
    ]
    for i, (x, y) in enumerate(spiral_pts):
        lines.append(f"G1 X{x:.3f} Y{y:.3f}")

    # ── 5. END ────────────────────────────────────────────────
    lines += [
        "",
        "; =====================================================",
        "; Done",
        "; =====================================================",
        f"G0 F{FEED_TRAVEL} X0 Y0   ; return home",
        "M2                         ; end program",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    gcode = generate_gcode()

    output_file = "sand_pattern.gcode"
    with open(output_file, "w") as f:
        f.write(gcode)

    # Count stats
    move_lines = sum(1 for l in gcode.splitlines() if l.startswith("G1"))
    print(f"✓ GCode written to '{output_file}'")
    print(f"  Total G1 moves : {move_lines}")
    print(f"  Spiral steps   : {SPIRAL_STEPS}")
    print(f"  Bed size       : {BED_W}×{BED_H} mm")
    print()
    print("Next steps:")
    print("  1. Run this script  → produces sand_pattern.gcode")
    print("  2. Open UGS / bCNC / Candle")
    print("  3. Connect to Arduino at 115200 baud")
    print("  4. Home machine ($H)")
    print("  5. Load & send sand_pattern.gcode")
